### ISSUE TITLE
Unable to verify a node with MFA

### ISSUE THREAD

**Issue by enestorovic** [synapsepay/SynapsePayRest-Ruby#10]
Since the latest version (0.0.13) I am always getting the following response when calling client.nodes.verify(payload: mfa_payload) while it is still working correctly in version 0.0.11.

Error response:
{
    "success" => false,
     "reason" => "The method is not allowed. Check your id parameters."
}

**Comment by stevula** [comment]
@enestorovic this is probably caused by ea9edf7. We needed to revert some changes there to allow microdeposit verification again. 

Are you calling Nodes#verify with a node_id or just the payload? Also, how is your `mfa_payload` structured? (please use fake values if this is production data)
