### ISSUE TITLE
add support for transaction idempotency keys

### ISSUE THREAD

**Issue by stevula** [synapsepay/SynapsePayRest-Ruby#34]

**Comment by javierjulio** [comment]
This is critical. I understand why its not in the codebase. The way the HTTPClient is setup I don't think is right and makes it very difficult to set anything else other than params (e.g. headers). Is this being being worked on? I have it in my gem but to starting using this one this is a deal breaker. I'd like to contribute.

**Comment by stevula** [comment]
@teganduong is working on this feature right now. Yes, updating headers is a convoluted process under the current design. We are planning to have `Transaction#create` take an optional `idempotency_key` argument which will call something like `self.node.user.client#update_headers(idempotency_key: "foo")`. 

I agree HTTPClient (and possible Client) have some issues. We are definitely open to ideas and collaboration on that aspect (while preserving backwards compatibility as much as possible).

**Comment by javierjulio** [comment]
That won't work though since you're mutating the client and thus would affect other requests too if reused since. The header should only apply for that one request. If anything the `post` method of the HTTPClient should take options and merge that header in that way its not permanent. I've been working on this anyway as its critical I have this and I wasn't sure how soon you'd get this out.

**Comment by stevula** [comment]
That makes sense. If you want to incorporate your changes here I think that would be an improvement.

**Comment by javierjulio** [comment]
@stevula ok I believe I have this update done. At first I was editing the wrong thing but then realized there are two code paths for creating transactions. I have them both updated and tested. Right now I'm running all other transaction related tests to make sure other functionality is unaffected. @teganduong I should have a PR for review up shortly. I'm happy to make any changes you deem necessary. Thanks.

**Comment by stevula** [comment]
#53
