### ISSUE TITLE
Releasing library with all changes for the current v3.1 API

### ISSUE THREAD

**Issue by javierjulio** [synapsepay/SynapsePayRest-Ruby#58]
Giving this more thought I think the overall approach for v3 of this SDK is wrong. This and other changes submitted should be made for a v2.x of the library and the current supported API. I think its great you want to develop for something that is new but keep in mind its first still not available ([not publicly listed](https://docs.synapsepay.com/versions)), second you mention it will be in sandbox for an extended amount of time before being in production (extending the time anyone can even use this updated library), and third Synapse made a hard case for using SDKs after putting out a notice for ending old KBA process in March. This makes transition difficult for us since several basic and critical features to our business are not available in the latest (or earlier) SDK version that supports the current API available.

**Comment by stevula** [comment]
Since most of the users of this library have not gone to production yet (still in sandbox mode), and the remaining lifespan of synapse_pay_rest-2.x is pretty short, I didn't see the need to make those updates available. But yes, we could do this fairly easily with better branch management.

**Comment by javierjulio** [comment]
Those updates should be available. You have several users that are currently on Synapse in production. We've been using Synapse for a long time now. I'm making a strong case here to make these updates available for your new users but existing ones since I was lead to believe that this is where the SDK was headed. Myself (as well as others) received an email about KYC 1.0 being EOL on March 2017 along with mention of using your new libraries.

> We have updated our Python, Ruby, and Node libraries! Restructured classes, improved error handling & some new convenience methods.
> Visit our blog to read more about these updates.
> Also, please remember that we will be shutting down KYC 1.0 APIs by end of March 2017.
> The following APIs will be affected:
> https://docs.synapsepay.com/docs/add-virtual-doc
> https://docs.synapsepay.com/docs/answer-kba
> https://docs.synapsepay.com/docs/add-physical-doc
> All of these API calls have been consolidated into this one API call: https://docs.synapsepay.com/docs/adding-documents
> If you are unaware of this API change, please read this blog post.
> If you have any questions about the implementation, please feel free to reach out to us on our discuss page or email hello@synapsepay.com.

I think its great you have a team dedicated to the SDKs. It really needed that. I'd like to continue to help  but I think its important to get updates out for your existing users that want to start using this SDK (whether they are or not) so they can move to KYC 2.0. I don't want to build the necessary updates to a library to support KYC 2.0 and then also switch to using this SDK. I can see your point of view is just from new users that have started to use the SDK but keep in mind you have several existing ones you're alienating.

**Comment by stevula** [comment]
Sorry, I didn't mean to suggest we weren't supporting existing users. When I referred to users of the library still being in sandbox mode, I was referring to those using the [new interface](https://github.com/synapsepay/SynapsePayRest-Ruby/tree/master/lib/synapse_pay_rest/models). My assumption was that existing production users would continue to use the [old interface](https://github.com/synapsepay/SynapsePayRest-Ruby/tree/master/lib/synapse_pay_rest/api). That assumption seems to have been incorrect, so we'll work on getting those features for 2.x users as well.

Anyways, your help is greatly appreciated, Javier. I do want to point out though, the older version of the library is capable of KYC 2.0 calls. You just have to the [Users#update](https://github.com/synapsepay/SynapsePayRest-Ruby/blob/master/lib/synapse_pay_rest/api/users.rb#L98) method and build the payload according to the docs ([adding docs](https://docs.synapsepay.com/docs/adding-documents) | [editing docs](https://docs.synapsepay.com/docs/updating-existing-document).

**Comment by stevula** [comment]
#61 adds conditional handling of the different API responses for API v3.1 (live in production) and v3.1.1 (live in sandbox). Everything else should be backwards compatible already.
