### ISSUE TITLE
Calling attach_doc with url raises NoMethodError content_type of NilClass

### ISSUE THREAD

**Issue by Lcarvajal** [synapsepay/SynapsePayRest-Ruby#6]
`SynapsePayRest-Ruby/lib/synapse_pay_rest/api/users.rb`

* The line `MIME::Types.type_for(file_path).first.content_type` should be `MIME::Types.type_for(file_path).first.try(:content_type)` or `MIME::Types.type_for(file_path).first` to check if the type exists.
* Users should be given the option to specify a file type if it isn't determined.
* Currently a call like `client.users.attach_file(file_path: 'https://s3.amazonaws.com/tipyourselfbetaphotos/users/images/000/000/220/med/image.png?1460395815')` would crash the app.

**Comment by stevula** [comment]
resolved by #5
