### ISSUE TITLE
Why are all KBA related methods deprecated?

### ISSUE THREAD

**Issue by javierjulio** [synapsepay/SynapsePayRest-Ruby#60]
When working with the virtual document for a user from the samples, I noticed all the methods in VirtualDocument class are deprecated. Is KBA no longer necessary on KYC 2.0? I'm trying to move to using that since its EOL at the end of March. I don't see any confirmation. The Sandbox API still returns questions/answers, so wouldn't these methods still need to be supported? They all use the new API for creating/updating documents. I'm very confused.

**Comment by stevula** [comment]
SSN MFA will be disabled in API v3.1.1

**Comment by javierjulio** [comment]
Will API v3.1.1 be in production before March?

**Comment by stevula** [comment]
I don't have an exact ETA for the upgrade date. The SSN MFA deactivation will happen at the same time.

**Comment by javierjulio** [comment]
Ok thanks. I ask as it could save me a good amount of time. I see examples for full SSN but we only provide the last 4 digits of the SSN. Just to verify, the MFA deactivation is for both?

**Comment by stevula** [comment]
Instead of a partial match (MFA|PENDING), you will just get SUBMITTED|INVALID for those SSNs. Last 4 is more likely to return ambiguous results (= partial match = invalid), so we recommend collecting full SSN if possible. With KYC 2.0 you can also specify fallback forms of documentation, so you might want to talk to your account manager about that if interested.

**Comment by javierjulio** [comment]
Ok so that's a very important distinction. If using last 4 digits of SSN, even with KYC 2.0 the KBA process would still be enabled?

**Comment by stevula** [comment]
There will be no KBA for SSN regardless of SSN length. SSNs that previously would have triggered KBA (SUBMITTED|MFA_PENDING) will just be treated as invalid (SUBMITTED|INVALID).
